This notebook is just so I have a number to quote in the intro of the manuscript.

In [1]:
import csv
import pandas as pd
import numpy as np

import matplotlib.pylab as pylab
params = {'legend.fontsize': 'large',
         'axes.labelsize': 'x-large',
         'axes.titlesize':'x-large',
         'xtick.labelsize':'large',
         'ytick.labelsize':'large'}
pylab.rcParams.update(params)

path = '/Users/chrislam/Desktop/gaspery/'

In [2]:
exofop = pd.read_csv(path+'exofop.csv')

In [5]:
exofop.dropna(subset=['TOI']).drop_duplicates(subset=['TOI'])

,Row ID,TIC ID,TIC,TOI,Telescope,Instrument,Spectral Resolution (R),Wavelengh coverage,SNR/resolution element,SNR wavelength,Appropriate to PRVs,Obs Date,User,User ID,Group,Tag,Notes
0,17221,4711,NaN,TOI 3129,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,30.3,5110 Angstroms,No,2021-06-06,bieryla,7,NaN,97548,NaN
16,17222,17361,cTOI 17361,TOI 3127,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,23.2,5110 Angstroms,No,2021-06-06,bieryla,7,NaN,97549,NaN
18,29253,47667,NaN,TOI 6560,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,31.7,5110 Angstroms,No,2024-03-31,bieryla,7,NaN,439373,NaN
49,25462,909930,NaN,TOI 5287,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,31.1,5110 Angstroms,No,2022-06-05,bieryla,7,NaN,416365,NaN
51,1147,1003831,NaN,TOI 564,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,34.2,5110 Angstroms,No,2019-04-16,bieryla,7,NaN,3192,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24908,29287,1884091865,NaN,TOI 1697,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,14.3,5110 Angstroms,No,2024-03-22,bieryla,7,NaN,439408,NaN
24911,29043,1980725947,NaN,TOI 3625,Keck (10 m),HIRES,50000,3600 to 9000 Angstroms,80,5000 Angstroms,No,2022-07-31,giacalone,117,NaN,438531,NaN
24912,29044,2010186093,NaN,TOI 3571,Keck (10 m),HIRES,50000,3600 to 9000 Angstroms,80,5000 Angstroms,No,2022-09-04,giacalone,117,NaN,438531,NaN
24913,29045,2016376984,NaN,TOI 3920,Keck (10 m),HIRES,50000,3600 to 9000 Angstroms,80,5000 Angstroms,No,2022-07-20,giacalone,117,NaN,438531,NaN
24914,20664,2041563029,NaN,TOI 1427,NOT (2.6 m),FIES,67000,3760 to 8220 Angstroms,24.0,5200 Angstroms,Yes,2019-11-27,buchhave,51,tfopwg,106967,NaN

In [16]:
archive = pd.read_csv(path+'PS_2024.04.10_12.49.19.csv')
archive = archive.dropna(subset=['tic_id'])
archive['tic_id'] = archive['tic_id'].str.replace(r'TIC ', '', regex=True).astype(int)

#archive['tic_id'] = 
archive

,pl_name,hostname,tic_id,default_flag,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,soltype,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,AU Mic b,AU Mic,441420236,1,1,3,Transit,2020,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.100,4.529,0.020,-0.020,7.84038,0.000731,-0.000731,2022-05-09,2021-12,2022-05-09
1,AU Mic c,AU Mic,441420236,1,1,3,Transit,2021,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.100,4.529,0.020,-0.020,7.84038,0.000731,-0.000731,2022-05-09,2021-12,2022-05-09
2,DS Tuc A b,DS Tuc A,410214986,1,2,1,Transit,2019,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.030,6.676,0.034,-0.034,8.31926,0.001025,-0.001025,2019-07-03,2019-07,2019-07-11
3,GJ 1252 b,GJ 1252,370133522,1,1,1,Transit,2020,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.200,7.915,0.023,-0.023,11.23640,0.000806,-0.000806,2023-07-10,2022-09,2023-07-10
4,GJ 143 b,GJ 143,279741379,1,1,2,Transit,2019,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.030,5.375,0.024,-0.024,7.67906,0.000260,-0.000260,2019-04-22,2019-04,2019-04-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,WASP-18 c,WASP-18,100100827,1,2,2,Transit Timing Variations,2019,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.030,8.131,0.027,-0.027,9.16617,0.000236,-0.000236,2019-12-02,2019-12,2019-12-05
428,WASP-84 c,WASP-84,350293646,1,1,2,Transit,2023,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.011,8.855,0.023,-0.023,10.57450,0.000590,-0.000590,2023-07-10,2023-06,2023-07-10
429,WD 1856+534 b,WD 1856+534,267574918,1,3,1,Transit,2020,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.046,15.548,0.186,-0.186,16.95800,0.000967,-0.000967,2020-12-10,2020-09,2020-12-17
430,Wolf 327 b,Wolf 327,4918918,1,1,1,Transit,2024,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.062,8.435,0.017,-0.017,11.95220,0.000646,-0.000646,2024-02-05,2024-01,2024-02-05
431,pi Men c,HD 39091,261136679,1,1,3,Transit,2018,Transiting Exoplanet Survey Satellite (TESS),Published Confirmed,...,-0.030,4.241,0.027,-0.027,5.51280,0.001946,-0.001946,2023-06-14,2022-09,2023-06-14

In [22]:
list(exofop.merge(archive, how='inner', left_on='TIC ID', right_on='tic_id').columns)

['Row ID',
 'TIC ID',
 'TIC',
 'TOI',
 'Telescope',
 'Instrument',
 'Spectral Resolution (R)',
 'Wavelengh coverage',
 'SNR/resolution element',
 'SNR wavelength',
 'Appropriate to PRVs',
 'Obs Date',
 'User',
 'User ID',
 'Group',
 'Tag',
 'Notes',
 'pl_name',
 'hostname',
 'tic_id',
 'default_flag',
 'sy_snum',
 'sy_pnum',
 'discoverymethod',
 'disc_year',
 'disc_facility',
 'soltype',
 'pl_controv_flag',
 'pl_refname',
 'pl_orbper',
 'pl_orbpererr1',
 'pl_orbpererr2',
 'pl_orbperlim',
 'pl_orbsmax',
 'pl_orbsmaxerr1',
 'pl_orbsmaxerr2',
 'pl_orbsmaxlim',
 'pl_rade',
 'pl_radeerr1',
 'pl_radeerr2',
 'pl_radelim',
 'pl_radj',
 'pl_radjerr1',
 'pl_radjerr2',
 'pl_radjlim',
 'pl_bmasse',
 'pl_bmasseerr1',
 'pl_bmasseerr2',
 'pl_bmasselim',
 'pl_bmassj',
 'pl_bmassjerr1',
 'pl_bmassjerr2',
 'pl_bmassjlim',
 'pl_bmassprov',
 'pl_orbeccen',
 'pl_orbeccenerr1',
 'pl_orbeccenerr2',
 'pl_orbeccenlim',
 'pl_insol',
 'pl_insolerr1',
 'pl_insolerr2',
 'pl_insollim',
 'pl_eqt',
 'pl_eqterr1',
 'pl_eqterr2',
 'pl_eqtlim',
 'ttv_flag',
 'st_refname',
 'st_spectype',
 'st_teff',
 'st_tefferr1',
 'st_tefferr2',
 'st_tefflim',
 'st_rad',
 'st_raderr1',
 'st_raderr2',
 'st_radlim',
 'st_mass',
 'st_masserr1',
 'st_masserr2',
 'st_masslim',
 'st_met',
 'st_meterr1',
 'st_meterr2',
 'st_metlim',
 'st_metratio',
 'st_logg',
 'st_loggerr1',
 'st_loggerr2',
 'st_logglim',
 'sy_refname',
 'rastr',
 'ra',
 'decstr',
 'dec',
 'sy_dist',
 'sy_disterr1',
 'sy_disterr2',
 'sy_vmag',
 'sy_vmagerr1',
 'sy_vmagerr2',
 'sy_kmag',
 'sy_kmagerr1',
 'sy_kmagerr2',
 'sy_gaiamag',
 'sy_gaiamagerr1',
 'sy_gaiamagerr2',
 'rowupdate',
 'pl_pubdate',
 'releasedate']

In [23]:
exofop.merge(archive, how='inner', left_on='TIC ID', right_on='tic_id').drop_duplicates(subset='pl_name')

,Row ID,TIC ID,TIC,TOI,Telescope,Instrument,Spectral Resolution (R),Wavelengh coverage,SNR/resolution element,SNR wavelength,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,1147,1003831,NaN,TOI 564,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,34.2,5110 Angstroms,...,-0.014,9.604,0.022,-0.022,11.14240,0.000599,-0.000599,2021-02-08,2020-11,2021-02-11
3,19779,4646810,NaN,TOI 461,NOT (2.6 m),FIES,67000,3760 to 8220 Angstroms,78.2,5200 Angstroms,...,-0.030,7.459,0.023,-0.023,9.47728,0.000512,-0.000512,2023-06-27,2023-08,2023-06-27
4,19779,4646810,NaN,TOI 461,NOT (2.6 m),FIES,67000,3760 to 8220 Angstroms,78.2,5200 Angstroms,...,-0.030,7.459,0.023,-0.023,9.47728,0.000512,-0.000512,2023-06-27,2023-08,2023-06-27
37,26153,4918918,cTOI 4918918,TOI 5747,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,26.0,5110 Angstroms,...,-0.062,8.435,0.017,-0.017,11.95220,0.000646,-0.000646,2024-02-05,2024-01,2024-02-05
39,16724,7548817,cTOI 7548817,TOI 2583,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,19.6,5110 Angstroms,...,-0.150,11.245,NaN,NaN,12.45920,0.000168,-0.000168,2023-02-27,2023-03,2023-02-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3703,26092,466382581,cTOI 466382581,TOI 5803,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,26.8,5110 Angstroms,...,-0.011,8.684,0.021,-0.021,10.47820,0.000683,-0.000683,2023-05-26,2023-01,2023-05-26
3705,3944,467179528,NaN,TOI 1266,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,12.4,5110 Angstroms,...,-0.049,8.840,0.020,-0.020,12.12220,0.000249,-0.000249,2024-03-25,2024-01,2024-03-25
3706,3944,467179528,NaN,TOI 1266,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,12.4,5110 Angstroms,...,-0.049,8.840,0.020,-0.020,12.12220,0.000249,-0.000249,2024-03-25,2024-01,2024-03-25
3711,5832,468574941,NaN,TOI 2046,FLWO (1.5 m),TRES,44000,3850 to 9096 Angstroms,28.1,5110 Angstroms,...,-0.018,10.094,0.023,-0.023,11.41280,0.000457,-0.000457,2022-05-23,2022-05,2022-05-23
3714,15551,470381900,NaN,TOI 1696,IRTF (3 m),SpeX,2000,0.7 to 2.55 microns,NaN,NaN,...,-1.133,11.331,0.023,-0.023,15.33140,0.000421,-0.000421,2022-06-27,2022-06,2022-06-27